version: '3'

services:
  api:
    image: "andrelugomes/api-invoice:latest"
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql

  etl:
    image: "andrelugomes/etl-invoice:latest"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoices